---
- name: Install Docker
  command: yum install -y docker

- name: Start Docker service
  systemd:
    name: docker
    state: started
    enabled: yes
  notify: restart docker

- name: Add users to docker group
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  loop: "{{ docker_users }}"