name: Release Images

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  user-service:
    uses: ./.github/workflows/reusable-image.yml
    with:
      service: user-service
    secrets: inherit

  product-service:
    uses: ./.github/workflows/reusable-image.yml
    with:
      service: product-service
    secrets: inherit

  order-service:
    uses: ./.github/workflows/reusable-image.yml
    with:
      service: order-service
    secrets: inherit